version: "3.3"

volumes:
  postgres_data:
  static_data:
  media_data:  # This can be removed if not used

services:
  db:
    image: postgres:13.0-alpine
    container_name: bigcorp-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: bigcorp-backend
    env_file: .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    restart: always
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py collectstatic --noinput &&
                    gunicorn rshome.wsgi:application --bind 0.0.0.0:8000 &&
                    stripe listen --forward-to localhost:8000/payment/webhook-stripe/"

  redis:
    image: redis:7.2.3-alpine
    container_name: bigcorp-redis
    restart: unless-stopped

  celery:
    build: ./backend
    container_name: bigcorp-celery
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/static:/app/static  # Ensure static is also mounted in celery if needed
    restart: always
    command: celery -A rshome worker --loglevel=info --beat

  nginx:
    image: nginx:latest
    container_name: bigcorp-nginx
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - 80:80
    restart: always

  flower:
    image: mher/flower:latest  # Correct image
    container_name: bigcorp-flower
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery
      - backend
      - nginx
    restart: always
    command: flower -A rshome --broker=redis://redis:6379/0